fix: add missing return statement to dbus_monitor_close (#135)
This avoids the following error during build:
```
dbus_client.c: In function 'dbus_monitor_close':
dbus_client.c:52:1: error: no return statement in function returning non-void [-Werror=return-type]
   52 | }
      | ^
```